  private Exception returningException() {
    try {
      doSomething();
    } catch (Exception e) {
      return e;
    }
    return null;
  }

