  void foo2() throws MyException { // Compliant - unknown exception is thrown by qix
    qix();
  }

