  @Test
  public void exception_catched_in_loop() throws Exception {
    JavaCheckVerifier.verify("src/test/files/se/LoopExceptionField.java", seChecks());
  }

