  @Test
  public void should_fail_if_check_raise_more_issues_than_expected() throws Exception {
    try {
      MavenCheckVerifier.verify(FILENAME_ISSUES, new MavenFileScanner() {
        @Override
        public void scanFile(MavenFileScannerContext context) {
          context.reportIssue(this, 7, "Message1");
          context.reportIssue(this, 28, "Message2");
          context.reportIssue(this, 40, "Message3");
          context.reportIssue(this, 41, "extraMessage");
        }
      });
      Fail.fail();
    } catch (AssertionError e) {
      assertThat(e).hasMessage("Unexpected at [41]");
    }
  }

