  @Test
  public void should_fail_if_detect_issues_but_not_in_file() {
    try {
      MavenCheckVerifier.verify(POM_WITH_NO_ISSUE, new MavenFileScanner() {
        @Override
        public void scanFile(MavenFileScannerContext context) {
          context.reportIssue(this, 7, "Message1");
          context.reportIssue(this, 28, "Message2");
          context.reportIssue(this, 40, "Message3");
        }
      });
    } catch (AssertionError e) {
      assertThat(e).hasMessage("Unexpected at [7, 28, 40]");
    }
  }

