  private void fun2() throws IOException {
  }

