  @Test
  void try_catch_finally() throws Exception {
    String methodName = "tryCatch";
    String expectedCFG = "B0(Exit)\n" +
      "B1\n" +
      "Jumps to: B2 \n" +
      "B2\n" +
      "0: ALOAD\n" +
      "1: INVOKESPECIAL\n" +
      "2: ALOAD\n" +
      "3: INVOKESPECIAL\n" +
      "Jumps to: B3 B5(Exception:java.io.IOException) B7(Exception:!UncaughtException!) \n" +
      "B3\n" +
      "0: GETSTATIC\n" +
      "1: LDC\n" +
      "2: INVOKEVIRTUAL\n" +
      "GOTO Jumps to: B4 \n" +
      "B4\n" +
      "0: RETURN\n" +
      "Jumps to: B0 \n" +
      "B5\n" +
      "0: ASTORE\n" +
      "1: ALOAD\n" +
      "2: INVOKEVIRTUAL\n" +
      "Jumps to: B6 B7(Exception:!UncaughtException!) \n" +
      "B6\n" +
      "0: GETSTATIC\n" +
      "1: LDC\n" +
      "2: INVOKEVIRTUAL\n" +
      "GOTO Jumps to: B4 \n" +
      "B7\n" +
      "0: ASTORE\n" +
      "1: GETSTATIC\n" +
      "2: LDC\n" +
      "3: INVOKEVIRTUAL\n" +
      "4: ALOAD\n" +
      "5: ATHROW\n" +
      "Jumps to: B0 \n";
    assertCFGforMethod(methodName, expectedCFG);
  }

